### ISSUE TITLE
Doesn't compile on my windows 95 machine 

### ISSUE THREAD

**Issue by helenol** [ethz-asl/robust_point_cloud_registration#5]
I even modified autoexec.bat :(
Please help
I am at Leonhardstrasse 12, need personal assistance

**Comment by helenol** [comment]
@hitimo @rikba @philipoe

**Comment by rikba** [comment]
I have the same issue. Can you help us?

**Comment by philipoe** [comment]
Have you tried turning it on an off again?

**Comment by igilitschenski** [comment]
I think you have to stick to Windows 3.11 for (drunk) Workgroups. Win 95 not supported yet.
